2017-02-16T15:34:13.8738050+02:00 0HL2ME1VLECT3 [INF] Request starting HTTP/1.1 GET http://localhost:5000/api/demo   (e5be5b71)
2017-02-16T15:34:14.2238460+02:00 0HL2ME1VLECT3 [INF] Executing action method "ConsoleApplication.Contollers.DemoController.Get (webapi-samples)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2017-02-16T15:34:14.2279070+02:00 0HL2ME1VLECT3 [INF] Hello (715ce7ec)
2017-02-16T15:34:14.2661000+02:00 0HL2ME1VLECT3 [INF] Executing ObjectResult, writing value "Microsoft.AspNetCore.Mvc.ControllerContext". (4e968210)
2017-02-16T15:34:14.4582790+02:00 0HL2ME1VLECT3 [INF] Executed action "ConsoleApplication.Contollers.DemoController.Get (webapi-samples)" in 302.9696ms (afa2e885)
2017-02-16T15:34:14.4701090+02:00 0HL2ME1VLECT3 [INF] Request finished in 623.8094ms 200 application/json; charset=utf-8 (15c52c40)
{"@t":"2017-02-16T13:41:48.5348760Z","@m":"Request starting HTTP/1.1 GET http://localhost:5000/api/demo  ","@i":"e5be5b71","Protocol":"HTTP/1.1","Method":"GET","ContentType":null,"ContentLength":null,"Scheme":"http","Host":"localhost:5000","PathBase":"","Path":"/api/demo","QueryString":"","HostingRequestStarting":"Request starting HTTP/1.1 GET http://localhost:5000/api/demo  ","EventId":{"Id":1},"SourceContext":"Microsoft.AspNetCore.Hosting.Internal.WebHost","RequestId":"0HL2ME675EESB","RequestPath":"/api/demo"}
{"@t":"2017-02-16T13:41:48.8677190Z","@m":"Executing action method \"ConsoleApplication.Contollers.DemoController.Get (webapi-samples)\" with arguments (null) - ModelState is Valid","@i":"ba7f4ac2","ActionName":"ConsoleApplication.Contollers.DemoController.Get (webapi-samples)","Arguments":null,"ValidationState":"Valid","EventId":{"Id":1},"SourceContext":"Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker","ActionId":"97fedd43-919e-4186-b91a-035cc0c92441","RequestId":"0HL2ME675EESB","RequestPath":"/api/demo"}
{"@t":"2017-02-16T13:41:48.8721200Z","@m":"Hello","@i":"715ce7ec","SourceContext":"ConsoleApplication.Contollers.DemoController","ActionId":"97fedd43-919e-4186-b91a-035cc0c92441","ActionName":"ConsoleApplication.Contollers.DemoController.Get (webapi-samples)","RequestId":"0HL2ME675EESB","RequestPath":"/api/demo"}
{"@t":"2017-02-16T13:41:48.9148660Z","@m":"Executing ObjectResult, writing value \"Microsoft.AspNetCore.Mvc.ControllerContext\".","@i":"4e968210","Value":"Microsoft.AspNetCore.Mvc.ControllerContext","EventId":{"Id":1},"SourceContext":"Microsoft.AspNetCore.Mvc.Internal.ObjectResultExecutor","ActionId":"97fedd43-919e-4186-b91a-035cc0c92441","ActionName":"ConsoleApplication.Contollers.DemoController.Get (webapi-samples)","RequestId":"0HL2ME675EESB","RequestPath":"/api/demo"}
{"@t":"2017-02-16T13:41:49.1057510Z","@m":"Executed action \"ConsoleApplication.Contollers.DemoController.Get (webapi-samples)\" in 311.0146ms","@i":"afa2e885","ActionName":"ConsoleApplication.Contollers.DemoController.Get (webapi-samples)","ElapsedMilliseconds":311.01460000000003,"EventId":{"Id":2},"SourceContext":"Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker","ActionId":"97fedd43-919e-4186-b91a-035cc0c92441","RequestId":"0HL2ME675EESB","RequestPath":"/api/demo"}
{"@t":"2017-02-16T13:41:49.1165410Z","@m":"Request finished in 612.4954ms 200 application/json; charset=utf-8","@i":"15c52c40","ElapsedMilliseconds":612.4954,"StatusCode":200,"ContentType":"application/json; charset=utf-8","HostingRequestFinished":"Request finished in 612.4954ms 200 application/json; charset=utf-8","EventId":{"Id":2},"SourceContext":"Microsoft.AspNetCore.Hosting.Internal.WebHost","RequestId":"0HL2ME675EESB","RequestPath":"/api/demo"}
2017-02-16T15:42:13.5087690+02:00 0HL2ME6EJK3RV [INF] Request starting HTTP/1.1 GET http://localhost:5000/api/demo   (e5be5b71)
2017-02-16T15:42:13.8514400+02:00 0HL2ME6EJK3RV [INF] Executing action method "ConsoleApplication.Contollers.DemoController.Get (webapi-samples)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2017-02-16T15:42:13.8557790+02:00 0HL2ME6EJK3RV [INF] Hello (715ce7ec)
2017-02-16T15:42:13.8960300+02:00 0HL2ME6EJK3RV [INF] Executing ObjectResult, writing value "Microsoft.AspNetCore.Mvc.ControllerContext". (4e968210)
2017-02-16T15:42:14.0882160+02:00 0HL2ME6EJK3RV [INF] Executed action "ConsoleApplication.Contollers.DemoController.Get (webapi-samples)" in 305.4715ms (afa2e885)
2017-02-16T15:42:14.0986210+02:00 0HL2ME6EJK3RV [INF] Request finished in 615.5406ms 200 application/json; charset=utf-8 (15c52c40)
2017-02-16T15:42:59.6873370+02:00 0HL2ME6SC06LF [INF] Request starting HTTP/1.1 GET http://localhost:5000/api/demo   (e5be5b71)
2017-02-16T15:43:00.0349520+02:00 0HL2ME6SC06LF [INF] Executing action method "ConsoleApplication.Contollers.DemoController.Get (webapi-samples)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2017-02-16T15:43:00.0396000+02:00 0HL2ME6SC06LF [INF] Hello 4 (a2d8011e)
2017-02-16T15:43:00.0776590+02:00 0HL2ME6SC06LF [INF] Executing ObjectResult, writing value "Microsoft.AspNetCore.Mvc.ControllerContext". (4e968210)
2017-02-16T15:43:00.2798300+02:00 0HL2ME6SC06LF [INF] Executed action "ConsoleApplication.Contollers.DemoController.Get (webapi-samples)" in 316.1589ms (afa2e885)
2017-02-16T15:43:00.2894880+02:00 0HL2ME6SC06LF [INF] Request finished in 626.68ms 200 application/json; charset=utf-8 (15c52c40)
2017-02-16T15:49:19.9705200+02:00 0HL2MEADMLRAT [INF] Request starting HTTP/1.1 GET http://localhost:5000/api/demo   (e5be5b71)
2017-02-16T15:49:20.3332620+02:00 0HL2MEADMLRAT [INF] Executing action method "ConsoleApplication.Contollers.DemoController.Get (webapi-samples)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2017-02-16T15:49:20.3418820+02:00 0HL2MEADMLRAT [INF] Hello 5 (b522a5b3)
2017-02-16T15:49:20.9420200+02:00 0HL2MEADMLRAT [INF] Executing ObjectResult, writing value "Microsoft.AspNetCore.Mvc.ControllerContext". (4e968210)
2017-02-16T15:49:21.0094250+02:00 0HL2MEADMLRAT [INF] Executed action "ConsoleApplication.Contollers.DemoController.Get (webapi-samples)" in 752.4389ms (afa2e885)
2017-02-16T15:49:21.0155920+02:00 0HL2MEADMLRAT [INF] Request finished in 1071.0947ms 200 text/plain; charset=utf-8 (15c52c40)
2017-02-16T15:53:10.2416060+02:00 0HL2MECIAMC9R [INF] Request starting HTTP/1.1 GET http://localhost:5000/api/demo   (e5be5b71)
2017-02-16T15:53:10.5879520+02:00 0HL2MECIAMC9R [INF] Executing action method "ConsoleApplication.Contollers.DemoController.Get (webapi-samples)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2017-02-16T15:53:11.1046010+02:00 0HL2MECIAMC9R [INF] Executing ObjectResult, writing value "Microsoft.AspNetCore.Mvc.ControllerContext". (4e968210)
2017-02-16T15:53:11.4283520+02:00 0HL2MECIAMC9R [INF] Executed action "ConsoleApplication.Contollers.DemoController.Get (webapi-samples)" in 910.5678ms (afa2e885)
2017-02-16T15:53:11.4376500+02:00 0HL2MECIAMC9R [INF] Request finished in 1220.8828ms 200 application/json; charset=utf-8 (15c52c40)
2017-02-16T17:10:29.2893250+02:00 0HL2MFNOS3I9N [INF] Request starting HTTP/1.1 GET http://localhost:5000/api/demo   (e5be5b71)
2017-02-16T17:10:29.6231800+02:00 0HL2MFNOS3I9N [INF] Executing action method "ConsoleApplication.Contollers.DemoController.Get (webapi-samples)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2017-02-16T17:10:30.3673320+02:00 0HL2MFNOS3I9N [ERR] Connection id ""0HL2MFNOQSHNV"": An unhandled exception was thrown by the application. (8c14976b)
MySql.Data.MySqlClient.MySqlException: Unable to connect to any of the specified MySQL hosts. ---> System.AggregateException: One or more errors occurred. (Device not configured) ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException: Device not configured
   at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
   at System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult)
   at System.Net.Dns.<>c.<GetHostAddressesAsync>b__14_1(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Sockets.TcpClient.<ConnectAsyncCorePrivate>d__65.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout)
   at MySql.Data.Common.StreamCreator.GetTcpStream(MySqlConnectionStringBuilder settings)
   at MySql.Data.Common.StreamCreator.GetStream(MySqlConnectionStringBuilder settings)
   at MySql.Data.MySqlClient.NativeDriver.Open()
   --- End of inner exception stack trace ---
   at MySql.Data.MySqlClient.NativeDriver.Open()
   at MySql.Data.MySqlClient.Driver.Open()
   at MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   at MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   at MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   at MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   at MySql.Data.MySqlClient.MySqlPool.GetConnection()
   at MySql.Data.MySqlClient.MySqlConnection.Open()
   at System.Data.Common.DbConnection.OpenAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dapper.SqlMapper.<ExecuteImplAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ConsoleApplication.Contollers.MyDataService.<SeedData>d__3.MoveNext() in /Users/anjmao/sources/dotnet-async-examples/src/webapi-samples/controllers/ApiDemoController.cs:line 49
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at ConsoleApplication.Contollers.DemoController.<Get>d__0.MoveNext() in /Users/anjmao/sources/dotnet-async-examples/src/webapi-samples/controllers/ApiDemoController.cs:line 21
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ObjectMethodExecutor.<CastToObject>d__40`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionFilterAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()
2017-02-16T17:10:30.3797870+02:00 0HL2MFNOS3I9N [INF] Request finished in 1115.2155ms 200  (15c52c40)
2017-02-16T17:10:45.2751360+02:00 0HL2MFNOS3I9O [INF] Request starting HTTP/1.1 GET http://localhost:5000/api/demo   (e5be5b71)
2017-02-16T17:10:45.2763640+02:00 0HL2MFNOS3I9O [INF] Executing action method "ConsoleApplication.Contollers.DemoController.Get (webapi-samples)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2017-02-16T17:10:45.7165060+02:00 0HL2MFNOS3I9O [ERR] Connection id ""0HL2MFNOQSHNV"": An unhandled exception was thrown by the application. (8c14976b)
MySql.Data.MySqlClient.MySqlException: Unable to connect to any of the specified MySQL hosts. ---> System.AggregateException: One or more errors occurred. (Device not configured) ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException: Device not configured
   at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
   at System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult)
   at System.Net.Dns.<>c.<GetHostAddressesAsync>b__14_1(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Sockets.TcpClient.<ConnectAsyncCorePrivate>d__65.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout)
   at MySql.Data.Common.StreamCreator.GetTcpStream(MySqlConnectionStringBuilder settings)
   at MySql.Data.Common.StreamCreator.GetStream(MySqlConnectionStringBuilder settings)
   at MySql.Data.MySqlClient.NativeDriver.Open()
   --- End of inner exception stack trace ---
   at MySql.Data.MySqlClient.NativeDriver.Open()
   at MySql.Data.MySqlClient.Driver.Open()
   at MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   at MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   at MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   at MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   at MySql.Data.MySqlClient.MySqlPool.GetConnection()
   at MySql.Data.MySqlClient.MySqlConnection.Open()
   at System.Data.Common.DbConnection.OpenAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dapper.SqlMapper.<ExecuteImplAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ConsoleApplication.Contollers.MyDataService.<SeedData>d__3.MoveNext() in /Users/anjmao/sources/dotnet-async-examples/src/webapi-samples/controllers/ApiDemoController.cs:line 49
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at ConsoleApplication.Contollers.DemoController.<Get>d__0.MoveNext() in /Users/anjmao/sources/dotnet-async-examples/src/webapi-samples/controllers/ApiDemoController.cs:line 21
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ObjectMethodExecutor.<CastToObject>d__40`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionFilterAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()
2017-02-16T17:10:45.7169140+02:00 0HL2MFNOS3I9O [INF] Request finished in 441.6022ms 200  (15c52c40)
2017-02-16T17:11:03.6135900+02:00 0HL2MFO33E301 [INF] Request starting HTTP/1.1 GET http://localhost:5000/api/demo   (e5be5b71)
2017-02-16T17:11:03.9548500+02:00 0HL2MFO33E301 [INF] Executing action method "ConsoleApplication.Contollers.DemoController.Get (webapi-samples)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2017-02-16T17:11:04.5082390+02:00 0HL2MFO33E301 [INF] Executing ObjectResult, writing value "Microsoft.AspNetCore.Mvc.ControllerContext". (4e968210)
2017-02-16T17:11:04.8223180+02:00 0HL2MFO33E301 [INF] Executed action "ConsoleApplication.Contollers.DemoController.Get (webapi-samples)" in 939.042ms (afa2e885)
2017-02-16T17:11:04.8309620+02:00 0HL2MFO33E301 [INF] Request finished in 1244.8765ms 200 application/json; charset=utf-8 (15c52c40)
2017-02-16T17:12:01.0722800+02:00 0HL2MFOK7DGMF [INF] Request starting HTTP/1.1 GET http://localhost:5000/api/demo   (e5be5b71)
2017-02-16T17:12:01.4185030+02:00 0HL2MFOK7DGMF [INF] Executing action method "ConsoleApplication.Contollers.DemoController.Get (webapi-samples)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2017-02-16T17:12:01.6444690+02:00 0HL2MFOK7DGMF [ERR] Connection id ""0HL2MFOK69F27"": An unhandled exception was thrown by the application. (8c14976b)
System.NotImplementedException: SSL not supported in this WinRT release.
   at MySql.Data.MySqlClient.NativeDriver.Open()
   at MySql.Data.MySqlClient.Driver.Open()
   at MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   at MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   at MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   at MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   at MySql.Data.MySqlClient.MySqlPool.GetConnection()
   at MySql.Data.MySqlClient.MySqlConnection.Open()
   at System.Data.Common.DbConnection.OpenAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dapper.SqlMapper.<ExecuteImplAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ConsoleApplication.Contollers.MyDataService.<SeedData>d__3.MoveNext() in /Users/anjmao/sources/dotnet-async-examples/src/webapi-samples/controllers/ApiDemoController.cs:line 49
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at ConsoleApplication.Contollers.DemoController.<Get>d__0.MoveNext() in /Users/anjmao/sources/dotnet-async-examples/src/webapi-samples/controllers/ApiDemoController.cs:line 20
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ObjectMethodExecutor.<CastToObject>d__40`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionFilterAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()
2017-02-16T17:12:01.6553000+02:00 0HL2MFOK7DGMF [INF] Request finished in 602.8573ms 200  (15c52c40)
2017-02-16T17:13:44.1571330+02:00 0HL2MFPIUG6AR [INF] Request starting HTTP/1.1 GET http://localhost:5000/api/demo   (e5be5b71)
2017-02-16T17:13:44.5329340+02:00 0HL2MFPIUG6AR [INF] Executing action method "ConsoleApplication.Contollers.DemoController.Get (webapi-samples)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2017-02-16T17:13:44.7746970+02:00 0HL2MFPIUG6AR [ERR] Connection id ""0HL2MFPIRVLOH"": An unhandled exception was thrown by the application. (8c14976b)
System.NotImplementedException: SSL not supported in this WinRT release.
   at MySql.Data.MySqlClient.NativeDriver.Open()
   at MySql.Data.MySqlClient.Driver.Open()
   at MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   at MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   at MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   at MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   at MySql.Data.MySqlClient.MySqlPool.GetConnection()
   at MySql.Data.MySqlClient.MySqlConnection.Open()
   at System.Data.Common.DbConnection.OpenAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dapper.SqlMapper.<ExecuteImplAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ConsoleApplication.Contollers.MyDataService.<SeedData>d__3.MoveNext() in /Users/anjmao/sources/dotnet-async-examples/src/webapi-samples/controllers/ApiDemoController.cs:line 49
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at ConsoleApplication.Contollers.DemoController.<Get>d__0.MoveNext() in /Users/anjmao/sources/dotnet-async-examples/src/webapi-samples/controllers/ApiDemoController.cs:line 20
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ObjectMethodExecutor.<CastToObject>d__40`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionFilterAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()
2017-02-16T17:13:44.7848730+02:00 0HL2MFPIUG6AR [INF] Request finished in 650.7816ms 200  (15c52c40)
2017-02-16T17:13:47.8278930+02:00 0HL2MFPIUG6AS [INF] Request starting HTTP/1.1 GET http://localhost:5000/api/demo   (e5be5b71)
2017-02-16T17:13:47.8291900+02:00 0HL2MFPIUG6AS [INF] Executing action method "ConsoleApplication.Contollers.DemoController.Get (webapi-samples)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2017-02-16T17:13:47.8330500+02:00 0HL2MFPIUG6AS [ERR] Connection id ""0HL2MFPIRVLOH"": An unhandled exception was thrown by the application. (8c14976b)
System.NotImplementedException: SSL not supported in this WinRT release.
   at MySql.Data.MySqlClient.NativeDriver.Open()
   at MySql.Data.MySqlClient.Driver.Open()
   at MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   at MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   at MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   at MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   at MySql.Data.MySqlClient.MySqlPool.GetConnection()
   at MySql.Data.MySqlClient.MySqlConnection.Open()
   at System.Data.Common.DbConnection.OpenAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dapper.SqlMapper.<ExecuteImplAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ConsoleApplication.Contollers.MyDataService.<SeedData>d__3.MoveNext() in /Users/anjmao/sources/dotnet-async-examples/src/webapi-samples/controllers/ApiDemoController.cs:line 49
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at ConsoleApplication.Contollers.DemoController.<Get>d__0.MoveNext() in /Users/anjmao/sources/dotnet-async-examples/src/webapi-samples/controllers/ApiDemoController.cs:line 20
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ObjectMethodExecutor.<CastToObject>d__40`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionFilterAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()
2017-02-16T17:13:47.8331830+02:00 0HL2MFPIUG6AS [INF] Request finished in 5.3866ms 200  (15c52c40)
2017-02-16T17:14:54.7990780+02:00 0HL2MFQ806KI1 [INF] Request starting HTTP/1.1 GET http://localhost:5000/api/demo   (e5be5b71)
2017-02-16T17:14:55.1555120+02:00 0HL2MFQ806KI1 [INF] Executing action method "ConsoleApplication.Contollers.DemoController.Get (webapi-samples)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2017-02-16T17:14:55.3712800+02:00 0HL2MFQ806KI1 [ERR] An unhandled exception has occurred while executing the request (cf926119)
System.NotImplementedException: SSL not supported in this WinRT release.
   at MySql.Data.MySqlClient.NativeDriver.Open()
   at MySql.Data.MySqlClient.Driver.Open()
   at MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   at MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   at MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   at MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   at MySql.Data.MySqlClient.MySqlPool.GetConnection()
   at MySql.Data.MySqlClient.MySqlConnection.Open()
   at System.Data.Common.DbConnection.OpenAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dapper.SqlMapper.<ExecuteImplAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ConsoleApplication.Contollers.MyDataService.<SeedData>d__3.MoveNext() in /Users/anjmao/sources/dotnet-async-examples/src/webapi-samples/controllers/ApiDemoController.cs:line 49
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at ConsoleApplication.Contollers.DemoController.<Get>d__0.MoveNext() in /Users/anjmao/sources/dotnet-async-examples/src/webapi-samples/controllers/ApiDemoController.cs:line 20
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ObjectMethodExecutor.<CastToObject>d__40`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionFilterAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
2017-02-16T17:14:55.5807290+02:00 0HL2MFQ806KI1 [INF] Request finished in 803.9589ms 500 text/html; charset=utf-8 (15c52c40)
2017-02-16T17:16:25.0190620+02:00 0HL2MFR2SJAFN [INF] Request starting HTTP/1.1 GET http://localhost:5000/api/demo   (e5be5b71)
2017-02-16T17:16:25.3710270+02:00 0HL2MFR2SJAFN [INF] Executing action method "ConsoleApplication.Contollers.DemoController.Get (webapi-samples)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2017-02-16T17:16:25.5917970+02:00 0HL2MFR2SJAFN [ERR] An unhandled exception has occurred while executing the request (cf926119)
System.NotImplementedException: SSL not supported in this WinRT release.
   at MySql.Data.MySqlClient.NativeDriver.Open()
   at MySql.Data.MySqlClient.Driver.Open()
   at MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   at MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   at MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   at MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   at MySql.Data.MySqlClient.MySqlPool.GetConnection()
   at MySql.Data.MySqlClient.MySqlConnection.Open()
   at System.Data.Common.DbConnection.OpenAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dapper.SqlMapper.<ExecuteImplAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ConsoleApplication.Contollers.MyDataService.<SeedData>d__3.MoveNext() in /Users/anjmao/sources/dotnet-async-examples/src/webapi-samples/controllers/ApiDemoController.cs:line 49
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at ConsoleApplication.Contollers.DemoController.<Get>d__0.MoveNext() in /Users/anjmao/sources/dotnet-async-examples/src/webapi-samples/controllers/ApiDemoController.cs:line 20
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ObjectMethodExecutor.<CastToObject>d__40`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionFilterAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
2017-02-16T17:16:25.8145730+02:00 0HL2MFR2SJAFN [INF] Request finished in 805.3654ms 500 text/html; charset=utf-8 (15c52c40)
2017-02-16T17:16:41.7184110+02:00 0HL2MFR7RRR9T [INF] Request starting HTTP/1.1 GET http://localhost:5000/api/demo   (e5be5b71)
2017-02-16T17:16:42.0748720+02:00 0HL2MFR7RRR9T [INF] Executing action method "ConsoleApplication.Contollers.DemoController.Get (webapi-samples)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2017-02-16T17:16:57.2927600+02:00 0HL2MFR7RRR9T [ERR] An unhandled exception has occurred while executing the request (cf926119)
MySql.Data.MySqlClient.MySqlException: Unable to connect to any of the specified MySQL hosts. ---> MySql.Data.MySqlClient.MySqlException: Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.
   at MySql.Data.Common.StreamCreator.GetTcpStream(MySqlConnectionStringBuilder settings)
   at MySql.Data.Common.StreamCreator.GetStream(MySqlConnectionStringBuilder settings)
   at MySql.Data.MySqlClient.NativeDriver.Open()
   --- End of inner exception stack trace ---
   at MySql.Data.MySqlClient.NativeDriver.Open()
   at MySql.Data.MySqlClient.Driver.Open()
   at MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   at MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   at MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   at MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   at MySql.Data.MySqlClient.MySqlPool.GetConnection()
   at MySql.Data.MySqlClient.MySqlConnection.Open()
   at System.Data.Common.DbConnection.OpenAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dapper.SqlMapper.<ExecuteImplAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ConsoleApplication.Contollers.MyDataService.<SeedData>d__3.MoveNext() in /Users/anjmao/sources/dotnet-async-examples/src/webapi-samples/controllers/ApiDemoController.cs:line 49
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at ConsoleApplication.Contollers.DemoController.<Get>d__0.MoveNext() in /Users/anjmao/sources/dotnet-async-examples/src/webapi-samples/controllers/ApiDemoController.cs:line 20
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ObjectMethodExecutor.<CastToObject>d__40`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionFilterAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
2017-02-16T17:16:57.5422310+02:00 0HL2MFR7RRR9T [INF] Request finished in 15844.4894ms 500 text/html; charset=utf-8 (15c52c40)
2017-02-16T17:17:31.8866970+02:00 0HL2MFRMQ9MC3 [INF] Request starting HTTP/1.1 GET http://localhost:5000/api/demo   (e5be5b71)
2017-02-16T17:17:32.2129410+02:00 0HL2MFRMQ9MC3 [INF] Executing action method "ConsoleApplication.Contollers.DemoController.Get (webapi-samples)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2017-02-16T17:17:35.6475020+02:00 0HL2MFRMQ9MC3 [INF] Executing ObjectResult, writing value "Microsoft.AspNetCore.Mvc.ControllerContext". (4e968210)
2017-02-16T17:17:35.9568830+02:00 0HL2MFRMQ9MC3 [INF] Executed action "ConsoleApplication.Contollers.DemoController.Get (webapi-samples)" in 3809.5702ms (afa2e885)
2017-02-16T17:17:35.9684730+02:00 0HL2MFRMQ9MC3 [INF] Request finished in 4102.5674ms 200 application/json; charset=utf-8 (15c52c40)
2017-02-16T17:20:59.1233820+02:00 0HL2MFTKILAQV [INF] Request starting HTTP/1.1 GET http://localhost:5000/api/demo   (e5be5b71)
2017-02-16T17:20:59.4778120+02:00 0HL2MFTKILAQV [INF] Executing action method "ConsoleApplication.Contollers.DemoController.Get (webapi-samples)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2017-02-16T17:20:59.8026070+02:00 0HL2MFTKILAQV [INF] Executing ObjectResult, writing value "Microsoft.AspNetCore.Mvc.ControllerContext". (4e968210)
2017-02-16T17:21:00.0472650+02:00 0HL2MFTKILAQV [INF] Executed action "ConsoleApplication.Contollers.DemoController.Get (webapi-samples)" in 649.766ms (afa2e885)
2017-02-16T17:21:00.0576090+02:00 0HL2MFTKILAQV [INF] Request finished in 957.154ms 200 application/json; charset=utf-8 (15c52c40)
